# -*- coding: utf-8 -*-
"""Text to Image Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCE9ZtARuuNKp4Y4nk2XVVghVKlOjg2g
"""

! pip install min-dalle -q

from min_dalle import MinDalle

model = MinDalle(is_mega=True, is_reusable=True)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "birds swimming in blood"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

